apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: rps-api

  template:
    metadata:
      labels:
        app: rps-api

    spec:
      containers:
        - name: rps-api
          image: rdanish/rps-api-go:latest

          ports:
            - containerPort: 8080

          env:
            - name: DB_USER
              value: root

            - name: DB_USER
              value: rpsuser
            
            - name: DB_PASSWORD
              value: rpspassword
            
            - name: DB_HOST
              value: mysql-service

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: rpsdb