// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/play": {
            "post": {
                "description": "Submit player choice and get game result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Play Rock Paper Scissors",
                "parameters": [
                    {
                        "description": "Player choice",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GameResponse"
                        }
                    }
                }
            }
        },
        "/stats": {
            "get": {
                "description": "Returns total wins, losses, draws and win percentage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Get game statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StatsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GameRequest": {
            "type": "object",
            "properties": {
                "choice": {
                    "type": "string"
                }
            }
        },
        "models.GameResponse": {
            "type": "object",
            "properties": {
                "computer_choice": {
                    "type": "string"
                },
                "player_choice": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                }
            }
        },
        "models.StatsResponse": {
            "type": "object",
            "properties": {
                "draws": {
                    "type": "integer"
                },
                "games_played": {
                    "type": "integer"
                },
                "losses": {
                    "type": "integer"
                },
                "win_percentage": {
                    "type": "number"
                },
                "wins": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Rock Paper Scissors API",
	Description:      "Cloud Native Rock Paper Scissors API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
